### ISSUE TITLE
it seems text_cb is not null terminated in pugixml version

### ISSUE THREAD

**Issue by tuananh** [simdsoft/xsxml#2]
I get this weird output when I use `no-recursive/xsxml.hpp`.

Works fine with rapidxml DOM parser version though.

The xml string is 

```
const char *xml = "<xml><hello attr=\"testattr\">world</hello></xml>";
```

```
startElement xml
startAttribute attr testattr
startElement hello
text world</hello></xml
endElement hello></xml
endElement xml
```

**Comment by halx99** [comment]
you should print content with length

**Comment by tuananh** [comment]
> you should print content with length

Thank you. Yes, I just realized it because in the example at `engine-x` repo, there wasn't len param so I had to take a look at xsxml repo.

https://github.com/simdsoft/engine-x/blob/master/cocos/platform/CCSAXParser.h#L56

**Comment by halx99** [comment]
by default, it use rapidxml stub, which will fill null term charactor at instrusive parse mode.
