### ISSUE TITLE
question: how to use this for stream parsing?

### ISSUE THREAD

**Issue by tuananh** [simdsoft/xsxml#4]
Hi,

First of all, thank you for creating this library.

I saw that parse expecting data length but for stream, I don't know that in advance.

how do I go about using this library to support stream parsing? is there an example for that?

**Comment by halx99** [comment]
you can see: https://github.com/simdsoft/engine-x/blob/master/cocos/platform/CCSAXParser.cpp

**Comment by halx99** [comment]
it's use for streaming parse for SpriteFrameCache

**Comment by tuananh** [comment]
Thanks
